### ISSUE TITLE
Organiser la repo et le code

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#1]
Faire les branches developp et main et tout
décider de comment faire si on veut porter des PR sur natur'adapt (vous le savez déjà pt etre)

**Comment by verovs** [comment]
Ha et surtout il faut repartir de la branche main et non developp de natur'adapt, celle-ci contient des WIP pas souhaitables

**Comment by verovs** [comment]
et enfin, j'ai juste fait un fork de la repo natur'adapt, je sais pas ce qu'il faut faire maintenant :D

**Comment by Spone** [comment]
J'ai créé une branche `main` (basée sur la branche `master` de Naturadapt) qui est la branche principale et qui sera déployée sur l'environnement de QA, ainsi que la branche `production` qui sera déployée sur l'environnement de production.

Pas de branches `master` ou `develop`.
