### ISSUE TITLE
annuaire des membres : ajout de filtres

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#10]
ajouter dans les filtres les nouveaux champs #3

**Comment by verovs** [comment]
Je ne peux pas encore clore ça . Ce sera clos qd la PR sera mergée sur main et déployée sur staging :)
les filtres ne sont pas encore lisibles. 

https://staging.nospollinisateurs.fr/groups/communaute/members

![Capture d’écran du 2023-03-02 17-18-24](https://user-images.githubusercontent.com/22638189/222488512-95c668cd-99ef-4108-bd8f-ac09bbd0dc26.png)

**Comment by Spone** [comment]
c'est déployé mais je pense qu'il faut relancer une commande pour remplir la base ?
