### ISSUE TITLE
trad anglaises apparaissent dans l'autocomplétion 

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#107]
Dans modifier son profil : 
quand on remplis le champ liste intérêts quand on tape animation de réseau on voit dans les suggestions "animation de réseau" ok et "network-animation"
prod / staging

si on tape "an" (prod/ staging) on a aussi project-managment qui apparait

c'est même pas les labels en plus parce que c'est les versions avec tirets

voir si y'en a d'autres

**Comment by verovs** [comment]
same dans l'annuaire /groups/communaute/members

**Comment by verovs** [comment]
Ok en fait ça aparait (hypothese actuelle) pour les skills qui existaient déjà mais pour lequel on a modifié le "nom à tiret" 
dans le fichier https://github.com/telabotanica/pollinisateurs/blob/main/translations/skills.fr.yml
il n'existe plus "network-animation" 
c'est devenu en ligne 62 network-facilitation: "animation de réseau"

il n'existe plus projectmanagment, c'est devenu ligne 66 project-set-up-and-management:
voir si ça le fais aussi pour les skills qu'on a supprimé carrément

**Comment by Spone** [comment]
@verovs peux-tu vérifier si le bug est toujours là sur staging ?

J'ai testé de :
- vider les tables `pollinisateurs_skills` et `pollinisateurs_users_skills`
- relancer `./bin/console import:skills` à la main en SSH sur le serveur

**Comment by verovs** [comment]
ça y est pluuuuus \o/  merci <3

**Comment by Spone** [comment]
Ok je fais la même manip sur prod du coup.

EDIT: c'est fait :heavy_check_mark:

**Comment by verovs** [comment]
merci bcp !! :)
