### ISSUE TITLE
Serveur : prod est super lent

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#110]
staging est lent mais c'est pas grave mais prod est aussi super lent, pour les "actions" : ie : créer / éditer une page
50s pour charger entièrement une page contenu  (texte uniquement) suite à une modif alors que j'ai des "trucs" en cache car je l'ai édité y'a qques minutes

![Capture d’écran du 2023-03-14 17-46-51](https://user-images.githubusercontent.com/22638189/225083789-275c0401-fd4d-481f-a0a1-290959e0a3fc.png)

**Comment by verovs** [comment]
![Capture d’écran du 2023-03-14 18-28-46](https://user-images.githubusercontent.com/22638189/225088856-cec7172b-be09-40a4-8441-496aed2bf77b.png)

le "fichier  edit" (petite tortue) prends 49 secondes c'est lui le pb

**Comment by Spone** [comment]
Pas de problème chez moi à l'instant

![image](https://user-images.githubusercontent.com/38524/225090182-a5b0aaac-ea37-45e1-bad5-fbc22307b694.png)

**Comment by verovs** [comment]
oh cool alors !!
