### ISSUE TITLE
lien unsubscribe sur les mails discussions de prod à enlever (ok en staging)

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#119]
Maintenant qu'on reçoit bien les mails  (merci encore <3)  Il y a une petite chose à corriger sur les mails discussion de prod

sur staging, le seul lien de désinscription des mail est celui lié au texte "Si vous ne souhaitez plus recevoir de notifications pour les discussions du groupe blabla"  (screen)
![Capture d’écran du 2023-03-21 14-21-56-edit](https://user-images.githubusercontent.com/22638189/226621179-ca22ab35-ca52-4113-9d84-746780b5c85e.png)

sur prod il y a ce même lien mais en bas du footer on a également un lien "unsubscribe" : celui-ci ne contient pas les mêmes "paramètres " que le précédent (c'est pas la même url au survol quoi) (screen)

![unsubscribe2](https://user-images.githubusercontent.com/22638189/226621229-d0083155-8007-4e28-9596-bb59293a4852.png)

Je ne sais même pas à quoi ça les désinscrit (je veux pas tester et me retrouver désinscrite de toutes les discussions :D  ).
Il faudrait enlever le lien de unsubscribe car il ne doit pas unsubscribe à ce qu'il faut

**Comment by Spone** [comment]
Fait, c'était bien dans la config Postmark, au niveau du Broadcast Stream :

![image](https://user-images.githubusercontent.com/38524/226656559-1d4e9c33-87e2-4e04-af9b-167e47ba3eed.png)
