### ISSUE TITLE
postmark

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#14]
La plateforme fonctionne avec le service tiers postmark. Il faut reprendre un abonnement et configurer le site et le service
penser au fait qu'on doit transférer le compte et la facturation (juin ? décembre ? je sais plus)

**Comment by Spone** [comment]
Serveur postmark créé.
Domaine nospollinisateurs.fr ajouté et configuré.

**Comment by Spone** [comment]
Configuration Postmark faite sur les applis de staging et de prod.
