### ISSUE TITLE
dé-natur'adaptiser le code

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#2]
Notes échanges avec Killian :

style généraliste + feuille de style alternatives qui viennent surcharger feuille de style générale
rendre feuille de style configurable : dossier style NA
dossier style OFB

variable d’environnement avec le nom de la déclinaison de style intéressant + builder webpack qui se base sur cet env pour intégrer surcharge

plausible à passer en environnement
tout le reste à l’air d’être déjà en environnement (bdd, nom plateforme, postmark etc)

**Comment by verovs** [comment]
j'ai noté ça mais y'a pt etre d'autres trucs et/ou d'autres façons de faire pour dé-naturadaptiser, je sais pas moi :)

**Comment by Spone** [comment]
Commencer par faire une recherche du terme `naturadapt` dans tout le code source.
