### ISSUE TITLE
Rendre le staging fonctionel ( : création de compte )

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#50]
je ne peux tjs pas créer de compte sur le staging
je comprends même pas pourquoi il cite le moteur de recherche en erreur principale

screens
pour reproduire : staging, créer compte

![Capture d’écran du 2023-02-22 10-39-45](https://user-images.githubusercontent.com/22638189/220582075-cedda43a-f9b5-41bb-85c3-0c0b7a072e51.png)
![Capture d’écran du 2023-02-22 10-40-14](https://user-images.githubusercontent.com/22638189/220582095-e3100922-3020-4c92-8446-c3edf037e3eb.png)

**Comment by Spone** [comment]
C'est réparé, il manquait cette commande à lancer en SSH ur le serveur pour créer les index de recherche vides :

```
php bin/console search:reindex:all
```
