### ISSUE TITLE
assigner rôle admin communauté à moi-même 

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#51]
une fois mon compte principal créé avec mon mail courant #50 
il faudrait me donner le rôle d'admin communauté pour que je puisse gérer mes comptes alts

**Comment by Spone** [comment]
Une fois inscrite, depuis phpMyAdmin, dans la colonne `roles`, remplacer `["ROLE_USER"]` par `["ROLE_USER", "ROLE_ADMIN"]`.

**Comment by Spone** [comment]
C'est fait.
