### ISSUE TITLE
Créer un groupe communauté

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#52]
je sais pas si je "peux le faire" ou si il faut que ce soit fait "en code"
C'est le groupe central où les gens sont inscrits de force (par défaut)
les admin de ce groupe ont le rôle d'admin sur tous les autres groupes par défaut

**Comment by Spone** [comment]
Il fallait créer le groupe depuis le site, puis passer le champ `is_active` à `1` dans PHPMyAdmin

https://staging.nospollinisateurs.fr/groups/communaute
