### ISSUE TITLE
Impossible de créer un groupe

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#53]
devrait être résolu une fois que #51 51 (voire #52  ? je pense pas) soit résolu

erreur lors de la création car il ne sait pas je pense à qui envoyer la validation, j'ai accès à la fonctionnalité de création de groupe "de base" celle où faut une valid (logique mon compte est lambda)
![Capture d’écran du 2023-02-22 15-19-03](https://user-images.githubusercontent.com/22638189/220650792-624a4520-0f1d-4948-aef1-f1ed1b51bb99.png)

![Capture d’écran du 2023-02-22 15-22-28](https://user-images.githubusercontent.com/22638189/220650760-845125d7-b415-4271-bf33-981cdd51a6ff.png)

**Comment by Spone** [comment]
J'ai pu créer un groupe : https://staging.nospollinisateurs.fr/groups/test-de-creation-de-groupe-prive
