### ISSUE TITLE
pas de mails reçu pour les discussions

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#54]
j'ai fait 2 discussions sur communauté via l'interface
https://staging.nospollinisateurs.fr/groups/communaute/discussions
j'ai rien reçu par mail :'( 
t'as reçu qque chose toi  @Spone  ?
j'ai checké sur postmark, j'ai accès à un dossier NP prod qui ne contient pas "de mouvements" (normal si c'est prod)

**Comment by Spone** [comment]
Non, rien reçu. Je vais regarder.

Je t'ai donné accès au serveur NP staging sur Postmark pour info.

**Comment by verovs** [comment]
cool du coup on voit bien que les transactionals sont ok mais y'a rien d'autre qui est passé

**Comment by Spone** [comment]
C'est sensé être instantané l'envoi des mails dans les discussions ?

**Comment by verovs** [comment]
oui ! testé en parallèle sur staging na et ça a été instant

**Comment by Spone** [comment]
J'ai à nouveau jeté un œil au code mais j'arrive pas à comprendre ce qui peut poser problème...

**Comment by verovs** [comment]
la doc trouvée, bon rédigée par toi même pas sûre d'être une aide https://github.com/telabotanica/naturadapt/issues/153

**Comment by verovs** [comment]
@arthur-tela  si tu peux regarder ça  ?

**Comment by Spone** [comment]
Je n'ai pas trouvé. J'atteins mes limites avec Symfony :/

Voilà ce que dit le support Postmark :

> is there anything else that might be different with the code you use for transactional and the one you're trying to use for a broadcast send? If transactional mail works, I can only think that it's code-related. It's also strange that even when you don't include the message stream parameter, it doesn't go through transactional instead. That makes it seem like there's something else happening with the request.

Je pense que les pistes à explorer sont :

- essayer de lever des exceptions quand les appels à l'API Postmark échouent (ce qui a l'air d'être le cas mais on a aucune visibilité) https://github.com/ActiveCampaign/swiftmailer-postmark#3-throw-exceptions-on-postmark-api-errors
- mettre à jour https://github.com/ActiveCampaign/postmark-php mais cela va sûrement impliquer pas mal de refactoring de [`BulkTransport`](https://github.com/telabotanica/pollinisateurs/blob/main/src/Postmark/BulkTransport.php) j'imagine

**Comment by kstefanini** [comment]
Bon alors en fait, pour construire le from des mails bulk je trouve que
`$from = 'noreply@' . $this->params[ 'list_domain' ];` est utilisé au lieu de `POSTMARK_SENDER`.
Donc forcément `noreply@list.nospollinisateurs.fr` et `noreply@list.staging.nospollinisateurs.fr` n'étant pas autorisées par Postmark ça marche moins bien.
J'ai corrigé la variable d'environnement et ça roule tout seul.
Idéalement faudrait revoir le code pour utiliser le client http de symfony et lire les codes d'erreur renvoyés dans le json par l'api. Postmark renvoie une http 200 même lorsque le sender n'est pas autorisé :
```
{"ErrorCode":400,"Message":"The 'From' address you supplied (noreply@list.nospollinisateurs.fr) is not a Sender Signature on your account. Please add and confirm this address in order to be able to use it in the 'From' field of your messages."}
```

**Comment by kstefanini** [comment]
Je suis allé trop vite, faut pas corriger les variables d'environnements, faut corriger le code >_<

**Comment by Spone** [comment]
Je peux aussi autoriser les senders `@lists.nospollinisateurs.fr` et `@lists.staging.nospollinisateurs.fr`, qu'en penses-tu ?

EDIT : je viens de vérifier, c'est ce qu'on avait fait pour Naturadapt

EDIT 2 : c'est fait

**Comment by kstefanini** [comment]
Ah bon bah je revert alors

**Comment by Spone** [comment]
En tout cas bien joué pour la résolution, j'étais complètement passé à côté de cette config quand j'ai fait ma review... :man_facepalming:
