### ISSUE TITLE
MdR de la page groupe > erreur search index (Warning: Undefined array key "search_texts")

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#55]
Attention ceci est présent aussi sur Natur'adapt (NA) (notes pour moi testé en parrallele sur staging, todo regarder sur prod :'(   l'erreur déclenchée me dis qque chose en plus, fouiner les tickets, - pour l'instant trouvé juste ça, pas l'erreur https://github.com/telabotanica/naturadapt/issues/296  )

Lorsqu'on fait une recherche(en étant connectée ou non et du coup membre du groupe ou non) via le **Moteur de Recherche (MdR)** dispo sur la page d'un groupe on déclenche une erreur.

lui 
![Capture d’écran du 2023-02-24 11-48-20](https://user-images.githubusercontent.com/22638189/221160393-2093dd67-7bff-4d85-83dd-754782c64932.png)

l'erreur
![image](https://user-images.githubusercontent.com/22638189/221158658-148705d4-37a7-4608-9c0d-bf85b6845ae2.png)

Lorsqu'on fait une recherche via le MdR du header on tombe bien sur le résultat de recherche

la diff visible est que lorsqu'on fait une recherche via le MdR groupe, l'url qui en résulte ne comprend pas de ""paramètres url" (trouve plus le nom) mais juste /search  :  https://staging.nospollinisateurs.fr/search

Alors que via la recherche header l'url affichée contient les "paramètres" query
NP : https://staging.nospollinisateurs.fr/search?form%5Bsearch_texts%5D%5Bquery%5D=tortue
NA : https://staging.naturadapt.etaminstudio.dev/search?form%5Bsearch_texts%5D%5Bquery%5D=parapluie

Groupe de test communauté Nos Pollinisateurs ( NP) en cherchant "tortue" https://staging.nospollinisateurs.fr/groups/communaute
Groupe test NA animatrice de point median en cherchant parapluie https://staging.naturadapt.etaminstudio.dev/groups/animateur--rice-de-point-median
(ces deux exemples sont basés sur des discussions mais cela fait pareil pour d'autres "types", cf. chercher castor sur NP pour résultat page et non discussion)

Mis en backlog, à traiter que si temps dispo

**Comment by verovs** [comment]
logique mais à noter que c'est pareil sur la "vue interface activités "du groupe (erreur lors de la recherche d'un terme)

https://staging.nospollinisateurs.fr/groups/communaute/events

![Capture d’écran du 2023-02-24 12-14-01](https://user-images.githubusercontent.com/22638189/221165784-9ba821a0-bef7-4590-8b6b-86245f9888e4.png)

**Comment by Spone** [comment]
#59 ne suffit pas à corriger le problème

**Comment by verovs** [comment]
me suis rappelée du truc "proche" (histoire d'url) c'est ici https://github.com/telabotanica/naturadapt/issues/347

**Comment by verovs** [comment]
ça marche :D
