### ISSUE TITLE
creation de groupe formulaire, url à modifier

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#58]
![Capture d’écran du 2023-02-27 16-18-15](https://user-images.githubusercontent.com/22638189/221604165-1ce2e1a4-d502-4a95-9b40-873e24cad136.png)
"Avant de commencer, jetez un œil à la page [Pourquoi créer un groupe ?](https://staging.naturadapt.etaminstudio.dev/groups/plateforme-web/pages/qui-peut-creer-des-groupes)"   le lien envoie sur 
https://staging.naturadapt.etaminstudio.dev/groups/plateforme-web/pages/qui-peut-creer-des-groupes

on va envoyer sur une page "aide" qu'on va créer dans communauté et qui servira à toute l'aide possible  . slug : communaute/aide

**Comment by verovs** [comment]
surement faire  "en environnement et pas en dur"

**Comment by Spone** [comment]
C'est fait côté variables d'environnement Clever Cloud, rien à changer dans le code.
