### ISSUE TITLE
créer prod et automatiser maj

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#7]
same as #6  mais pour la prod.

Il faut cependant attendre d'avoir le nom de la plateforme pour avoir le nom de domaine à prendre

**Comment by verovs** [comment]
le nom choisi c'est, comme celui de la maquette :D Nos pollinisateurs
du coup : nospollinisateurs.fr   ?

**Comment by Spone** [comment]
C'est fait. Merger #56 lancera la première mise en prod.
