### ISSUE TITLE
membres en attente  (inscription groupe privé)

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#73]
sur le XD https://xd.adobe.com/view/dd254f37-e5f8-4e08-a252-164e40864d72-8876/screen/e6e57219-d008-429d-971b-2a24264f86cd/

On peut voir dés la page d'accueil du groupe les membres qui sont en attente, dans la carte "membres" et mis en valeur par une ligne violette

ça n'existe pas en staging

![Capture d’écran du 2023-03-01 17-05-34](https://user-images.githubusercontent.com/22638189/222197734-0233cadd-99cc-44f5-bf83-4ef46ea4d9f8.png)

![Capture d’écran du 2023-03-01 17-05-40](https://user-images.githubusercontent.com/22638189/222196790-5529fdb4-ac52-4431-8da4-2ac97fb6a06f.png)

Je ne suis pas sûre de quelle techno ça mobilise de faire ça, si y'a du php ou pas, donc si on ne peut pas le faire ce n'est pas grave.

Par contre on voit (en tant qu'admin du groupe) les membres en attente dans la page /membres du groupe 
roups/groupename/members
voir en étant admin ici  https://staging.nospollinisateurs.fr/groups/groupe-prive-sur-les-abeilles/members

![Capture d’écran du 2023-03-01 17-05-19](https://user-images.githubusercontent.com/22638189/222196839-5c752d32-c994-404e-9cd8-1495ffeda3ae.png)

Est-ce qu'on pourrait modifier la ligne verte à côté de mimipoulpe (en attente de valid) par une ligne violette ici ?

**Comment by Spone** [comment]
> Est-ce qu'on pourrait modifier la ligne verte à côté de mimipoulpe (en attente de valid) par une ligne violette ici ?

Ça, c'est fait dans #92, le reste non.
