### ISSUE TITLE
Profile formulaire style

### ISSUE THREAD

**Issue by verovs** [telabotanica/pollinisateurs#75]
en plus des corrections de fond qui sont en cours (ajout d'un champ et modif 1 champ & txts et skills) il faut modifier du style, un peu comme pour 
#72 

lien https://staging.nospollinisateurs.fr/user/profile/edit

font, hauteur de ligne, parcourir en rose clair sans survol
![Capture d’écran du 2023-03-01 17-30-04](https://user-images.githubusercontent.com/22638189/222202178-4fac9613-a3a9-45d5-a697-fe91ad3f36ea.png)

**Comment by Spone** [comment]
@verovs Est-ce que la PR #79 n'a pas réglé tous les problèmes sur ce formulaire aussi ?

**Comment by verovs** [comment]
siii ! par contre , mais je crois pas que ce soit cette pr ça me semble pas logique mais mon milieu d'action est cassé (je rcoirs qu'il était pas cassé, 

![Capture d’écran du 2023-03-06 18-34-59](https://user-images.githubusercontent.com/22638189/223188133-40d75b59-f4de-4877-b4c7-f505a4c7f582.png)
