### ISSUE TITLE
Affichage filtre environnement

### ISSUE THREAD

**Issue by Spone** [telabotanica/pollinisateurs#90]
L'affichage des boutons radio est cassé :

https://staging.nospollinisateurs.fr/groups/communaute/members

![image](https://user-images.githubusercontent.com/38524/223185394-6e60c91e-89d2-46a8-a9bd-ced74dd1cd7b.png)

**Comment by arthur-tela** [comment]
Problème d'affichage réglé

**Comment by Spone** [comment]
Bien joué ! :fire:
